Add Codecov.io

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,6 +1,4 @@
 version: 2.1
-orbs:
-  codecov: lebaptiste/codecov@0.1.0
 jobs:
   build:
     docker:
@@ -37,6 +35,24 @@ jobs:
             - ~/.m2
           key: v1-dependencies-{{ checksum "pom.xml" }}
       - run: chmod -R 777 ./mvnw && pg_ctl start -D /var/lib/postgresql/data -l /var/lib/postgresql/log.log && ./mvnw verify -X -P jacoco
+      - run:
+          name: Upload Coverage Results
+          command: |
+            set -e
+            REPO_TOKEN=${<< parameters.repo_token_env_var >>}
+            if [ -z "${REPO_TOKEN}" ]; then
+              # git@github.com:owner/repo.git
+              REPO_NAME="${CIRCLE_REPOSITORY_URL##*:}"
+              # owner/repo.git
+              REPO_NAME="${REPO_NAME%%.git}"
+              API_TOKEN=${<< parameters.api_token_env_var >>}
+              REPO_TOKEN=$(curl -X GET "https://codecov.io/api/pub/gh/${REPO_NAME}/settings" -H "Authorization: token ${API_TOKEN:?}" | jq .repo.upload_token --raw-output)
+            fi
+            curl -s https://codecov.io/bash --show-error | bash -s -- \
+              -f ./target/coverage-reports/jacoco-ut.exec \
+              -t "${REPO_TOKEN}" \
+              -Z || echo 'Codecov upload failed'
+
       - codecov/upload:
           file: ./target/coverage-reports/jacoco-ut.exec
 
